inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

plugins: rubocop-on-rbs

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'

RBS:
  Enabled: true

Layout/IndentationConsistency:
  Exclude: ['*.md']

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/*'
