project_emoji: "🍲"
engines:
  - ruby
  - jruby
  - truffleruby
readme:
  top_logo_mode: org
licenses:
  - AGPL-3.0-only
  - PolyForm-Small-Business-1.0.0
machine_users:
  - autobolt
min_divergence_threshold: 5
templates:
  root: packaged
  apply: true
plugins:
  - kettle-drift
defaults:
  preference: template
  add_template_only_nodes: true
  freeze_token: kettle-jem
tokens:
  forge:
    gh_user: pboling
    gl_user: pboling
    cb_user: pboling
    sh_user: galtzo
  author:
    name: "Peter H. Boling"
    given_names: "Peter H."
    family_names: Boling
    email: "floss@galtzo.com"
    domain: galtzo.com
    orcid: 0009-0008-8519-441X
  funding:
    patreon: galtzo
    kofi: pboling
    paypal: peterboling
    buymeacoffee: pboling
    polar: pboling
    liberapay: pboling
    issuehunt: pboling
  social:
    mastodon: galtzo
    bluesky: galtzo.com
    linktree: galtzo
    devto: galtzo
patterns:
  -
    path: "certs/**"
    strategy: raw_copy
files:
  AGENTS.md:
    strategy: accept_template
  .github:
    copilot_instructions.md:
      strategy: accept_template
  gemfiles:
    modular:
      templating.gemfile:
        strategy: accept_template
      templating_local.gemfile:
        strategy: accept_template
